### ISSUE TITLE
support .org files

### ISSUE THREAD

**Issue by netpyoung** [emacs-jp/init-loader#21]
how about to support `.org` using `org-babel-load-file` function?

https://github.com/sniperliu/dotfiles/blob/master/.emacs.d/customizations/editing.org

**Comment by takaxp** [comment]
I'm not sure what you want to say, you mean `init-loader.el` could be tangled from `init-loader.org`? Could you provide more information in detail?

**Comment by netpyoung** [comment]
Currently init-loader load `.el` files using `load` function. like that
```
00_util.el
01_ik-cmd.el
21_javascript.el
99_global-keys.el
```

What I want is support `.org` files both. like that.
```
00_util.el
01_ik-cmd.org
21_javascript.org
99_global-keys.org
```

`.el` is just source code so It cannot be markup. but github support `.org` file for markup, so It will be good to write document on org-mode.

**Comment by takaxp** [comment]
I see, thanks :)

By manually, you can generate any elisp files for `init-loader.el` by emacs batch-mode.

For example,
```
emacs -q --script ~/Dropbox/config/tangle.el
```

you can write some functions to tangle any org files.

Yes, the native support to read org files in init-loader is an excellent idea 👍

**Comment by takaxp** [comment]
Or, `babel-loder.el` would help you.

see https://github.com/takaishi/babel-loader.el/blob/master/babel-loader.el

**Comment by netpyoung** [comment]
oh this issue still had been opened sorry.
