### ISSUE TITLE
travis build error

### ISSUE THREAD

**Issue by byplayer** [emacs-jp/init-loader#23]
There is an error to build travis.
It looks that emacs binary in ppa repository has gone.

**Comment by byplayer** [comment]
I created two branches.
One is to use docker directly and the other is to use docker-compose to clarify mounting volume.
https://github.com/emacs-jp/init-loader/compare/master...byplayer:feature/travis_environment
https://github.com/emacs-jp/init-loader/compare/master...byplayer:feature/travis_docker_compose

If either of the above seems fine, I will create a pull request.

**Comment by syohex** [comment]
Thanks for reporting issue. We have switched to github actions #24.
